-- HomeOffer.pro proxy bidding and listing-agent privacy
-- Apply once in the Supabase SQL editor.
--
-- Public behavior:
--   * A bidder stores a private maximum.
--   * The visible offer advances in exact $500 steps.
--   * Public history exposes only masked names, amount and time.
-- Private behavior:
--   * Only the listing agent assigned to the property can read bidder identity,
--     contact information and each bidder's private maximum.

begin;

create table if not exists public.offer_limits (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  bidder_id uuid not null references public.users(id) on delete cascade,
  maximum_amount bigint not null check (maximum_amount > 0 and maximum_amount % 500 = 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id, bidder_id)
);

create table if not exists public.offer_proxy_state (
  property_id uuid primary key references public.properties(id) on delete cascade,
  current_amount bigint not null,
  leader_bidder_id uuid references public.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.offer_bid_events (
  id bigint generated by default as identity primary key,
  property_id uuid not null references public.properties(id) on delete cascade,
  bidder_id uuid not null references public.users(id) on delete cascade,
  amount bigint not null check (amount > 0 and amount % 500 = 0),
  sequence_number bigint not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (property_id, sequence_number),
  unique (property_id, amount)
);

create index if not exists offer_limits_property_idx
  on public.offer_limits(property_id);
create index if not exists offer_bid_events_property_sequence_idx
  on public.offer_bid_events(property_id, sequence_number desc);

alter table public.offer_limits enable row level security;
alter table public.offer_proxy_state enable row level security;
alter table public.offer_bid_events enable row level security;

-- These tables are intentionally RPC-only. The functions below expose the
-- minimum appropriate view for each audience after checking auth.uid().
revoke all on public.offer_limits from anon, authenticated;
revoke all on public.offer_proxy_state from anon, authenticated;
revoke all on public.offer_bid_events from anon, authenticated;

create or replace function public.mask_bidder_name(first_name text, last_name text)
returns text
language sql
immutable
set search_path = public, pg_temp
as $$
  select
    coalesce(left(nullif(trim(first_name), ''), 1) || repeat('*', greatest(length(trim(first_name)) - 1, 0)), 'B*****')
    || ' ' ||
    coalesce(left(nullif(trim(last_name), ''), 1) || repeat('*', greatest(length(trim(last_name)) - 1, 0)), 'U***');
$$;

create or replace function public.place_max_offer(
  p_property_id uuid,
  p_maximum_amount bigint
)
returns table (
  current_amount bigint,
  bidder_maximum bigint,
  is_leading boolean,
  offer_end_date timestamptz,
  extended boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_bidder uuid := auth.uid();
  v_property public.properties%rowtype;
  v_state public.offer_proxy_state%rowtype;
  v_previous_limit bigint;
  v_leader_limit bigint;
  v_existing_leader uuid;
  v_amount bigint;
  v_next bigint;
  v_sequence bigint;
  v_extended boolean := false;
  v_visible_changed boolean := false;
begin
  if v_bidder is null then
    raise exception 'You must be signed in to submit an offer.';
  end if;

  if p_maximum_amount is null or p_maximum_amount <= 0 or p_maximum_amount % 500 <> 0 then
    raise exception 'Your maximum must be entered in exact $500 increments.';
  end if;

  select * into v_property
  from public.properties
  where id = p_property_id
  for update;

  if not found then
    raise exception 'Property not found.';
  end if;
  if v_property.status <> 'active' then
    raise exception 'This property is not accepting offers.';
  end if;
  if v_property.offer_end_date <= clock_timestamp() then
    raise exception 'The offer period has ended.';
  end if;
  if p_maximum_amount < v_property.starting_offer then
    raise exception 'Your maximum must be at least the starting offer of $%.', v_property.starting_offer;
  end if;
  if v_property.starting_offer::bigint % 500 <> 0 then
    raise exception 'The listing starting offer must be in exact $500 increments.';
  end if;

  if not exists (
    select 1 from public.agent_approvals aa
    where aa.property_id = p_property_id
      and aa.buyer_id = v_bidder
      and aa.approved = true
  ) then
    raise exception 'Listing-agent approval is required before you can submit an offer.';
  end if;

  select maximum_amount into v_previous_limit
  from public.offer_limits
  where property_id = p_property_id and bidder_id = v_bidder;

  if v_previous_limit is not null and p_maximum_amount <= v_previous_limit then
    raise exception 'Your new maximum must be higher than your existing maximum of $%.', v_previous_limit;
  end if;

  insert into public.offer_limits(property_id, bidder_id, maximum_amount)
  values (p_property_id, v_bidder, p_maximum_amount)
  on conflict (property_id, bidder_id) do update
    set maximum_amount = excluded.maximum_amount,
        updated_at = clock_timestamp();

  insert into public.offer_proxy_state(property_id, current_amount, leader_bidder_id)
  select p_property_id,
         coalesce(o.amount::bigint, v_property.starting_offer::bigint),
         o.buyer_id
  from (select 1) seed
  left join lateral (
    select buyer_id, amount
    from public.offers
    where property_id = p_property_id
    order by amount desc, created_at asc
    limit 1
  ) o on true
  on conflict (property_id) do nothing;

  select * into v_state
  from public.offer_proxy_state
  where property_id = p_property_id
  for update;

  v_amount := v_state.current_amount;
  v_existing_leader := v_state.leader_bidder_id;

  if v_existing_leader is not null then
    insert into public.offer_limits(property_id, bidder_id, maximum_amount)
    values (p_property_id, v_existing_leader, v_amount)
    on conflict (property_id, bidder_id) do nothing;
  end if;
  select coalesce(max(sequence_number), 0) into v_sequence
  from public.offer_bid_events
  where property_id = p_property_id;

  if v_state.leader_bidder_id is null then
    v_sequence := v_sequence + 1;
    insert into public.offer_bid_events(property_id, bidder_id, amount, sequence_number)
    values (p_property_id, v_bidder, v_amount, v_sequence)
    on conflict (property_id, amount) do nothing;
    v_state.leader_bidder_id := v_bidder;
    v_visible_changed := true;
  elsif v_state.leader_bidder_id = v_bidder then
    -- Raising the current leader's private limit does not change the visible price.
    null;
  else
    select maximum_amount into v_leader_limit
    from public.offer_limits
    where property_id = p_property_id
      and bidder_id = v_existing_leader;

    v_leader_limit := coalesce(v_leader_limit, v_amount);
    v_next := v_amount + 500;

    if p_maximum_amount < v_next then
      raise exception 'Your maximum must be at least $%.', v_next;
    end if;

    -- Materialize every $500 step. The challenger bids first; the existing
    -- leader answers when their limit permits. An equal maximum is won by the
    -- bidder who set that maximum first (the existing leader).
    loop
      if v_next > p_maximum_amount then
        exit;
      end if;

      if p_maximum_amount = v_leader_limit and v_next = p_maximum_amount then
        v_sequence := v_sequence + 1;
        insert into public.offer_bid_events(property_id, bidder_id, amount, sequence_number)
        values (p_property_id, v_existing_leader, v_next, v_sequence);
        v_amount := v_next;
        v_state.leader_bidder_id := v_existing_leader;
        v_visible_changed := true;
        exit;
      end if;

      v_sequence := v_sequence + 1;
      insert into public.offer_bid_events(property_id, bidder_id, amount, sequence_number)
      values (p_property_id, v_bidder, v_next, v_sequence);
      v_amount := v_next;
      v_state.leader_bidder_id := v_bidder;
      v_visible_changed := true;
      v_next := v_next + 500;

      if v_next > v_leader_limit then
        exit;
      end if;

      v_sequence := v_sequence + 1;
      insert into public.offer_bid_events(property_id, bidder_id, amount, sequence_number)
      values (p_property_id, v_existing_leader, v_next, v_sequence);
      v_amount := v_next;
      v_state.leader_bidder_id := v_existing_leader;
      v_visible_changed := true;
      v_next := v_next + 500;
    end loop;
  end if;

  update public.offer_proxy_state
  set current_amount = v_amount,
      leader_bidder_id = v_state.leader_bidder_id,
      updated_at = clock_timestamp()
  where property_id = p_property_id;

  -- Keep the legacy highest-offer view usable without storing private limits.
  if v_visible_changed then
    update public.offers set is_highest = false
    where property_id = p_property_id and is_highest = true;
    insert into public.offers(property_id, buyer_id, amount, is_highest)
    values (p_property_id, v_state.leader_bidder_id, v_amount, true);
  end if;

  if v_property.offer_end_date > clock_timestamp()
     and v_property.offer_end_date <= clock_timestamp() + interval '7 minutes' then
    update public.properties
    set offer_end_date = clock_timestamp() + interval '7 minutes'
    where id = p_property_id
    returning properties.offer_end_date into v_property.offer_end_date;
    v_extended := true;
  end if;

  return query select
    v_amount,
    p_maximum_amount,
    v_state.leader_bidder_id = v_bidder,
    v_property.offer_end_date::timestamptz,
    v_extended;
end;
$$;

create or replace function public.get_public_offer_history(p_property_id uuid)
returns table (
  sequence_number bigint,
  amount bigint,
  masked_bidder text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select e.sequence_number,
         e.amount,
         public.mask_bidder_name(u.first_name, u.last_name),
         e.created_at
  from public.offer_bid_events e
  join public.users u on u.id = e.bidder_id
  where e.property_id = p_property_id
  order by e.sequence_number desc;
$$;

create or replace function public.get_public_offer_summary(p_property_id uuid)
returns table (current_amount bigint, bid_count bigint)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(s.current_amount, p.starting_offer::bigint),
         (select count(*) from public.offer_bid_events e where e.property_id = p.id)
  from public.properties p
  left join public.offer_proxy_state s on s.property_id = p.id
  where p.id = p_property_id;
$$;

create or replace function public.get_my_offer_status(p_property_id uuid)
returns table (maximum_amount bigint, current_amount bigint, is_leading boolean)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select l.maximum_amount,
         s.current_amount,
         s.leader_bidder_id = auth.uid()
  from public.offer_limits l
  join public.offer_proxy_state s on s.property_id = l.property_id
  where l.property_id = p_property_id and l.bidder_id = auth.uid();
$$;

create or replace function public.get_listing_agent_bidder_details(p_property_id uuid)
returns table (
  bidder_id uuid,
  full_name text,
  email text,
  phone_number text,
  user_type text,
  maximum_amount bigint,
  visible_amount bigint,
  bid_steps bigint,
  first_bid_at timestamptz,
  last_bid_at timestamptz,
  is_leading boolean
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.properties p
    where p.id = p_property_id and p.listing_agent_id = auth.uid()
  ) then
    raise exception 'Only this property''s listing agent can view private bidder details.';
  end if;

  return query
  select l.bidder_id,
         trim(concat_ws(' ', u.first_name, u.last_name)),
         u.email::text,
         u.phone_number::text,
         u.user_type::text,
         l.maximum_amount,
         coalesce(max(e.amount), 0)::bigint,
         count(e.id)::bigint,
         min(e.created_at),
         max(e.created_at),
         s.leader_bidder_id = l.bidder_id
  from public.offer_limits l
  join public.users u on u.id = l.bidder_id
  join public.offer_proxy_state s on s.property_id = l.property_id
  left join public.offer_bid_events e
    on e.property_id = l.property_id and e.bidder_id = l.bidder_id
  where l.property_id = p_property_id
  group by l.bidder_id, u.first_name, u.last_name, u.email, u.phone_number,
           u.user_type, l.maximum_amount, s.leader_bidder_id
  order by l.maximum_amount desc, min(l.created_at);
end;
$$;

create or replace function public.get_listing_agent_bid_history(p_property_id uuid)
returns table (
  sequence_number bigint,
  amount bigint,
  bidder_id uuid,
  full_name text,
  email text,
  phone_number text,
  maximum_amount bigint,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.properties p
    where p.id = p_property_id and p.listing_agent_id = auth.uid()
  ) then
    raise exception 'Only this property''s listing agent can view private bid history.';
  end if;

  return query
  select e.sequence_number, e.amount, e.bidder_id,
         trim(concat_ws(' ', u.first_name, u.last_name)),
         u.email::text, u.phone_number::text, l.maximum_amount, e.created_at
  from public.offer_bid_events e
  join public.users u on u.id = e.bidder_id
  join public.offer_limits l
    on l.property_id = e.property_id and l.bidder_id = e.bidder_id
  where e.property_id = p_property_id
  order by e.sequence_number desc;
end;
$$;

revoke all on function public.place_max_offer(uuid, bigint) from public;
revoke all on function public.get_public_offer_history(uuid) from public;
revoke all on function public.get_public_offer_summary(uuid) from public;
revoke all on function public.get_my_offer_status(uuid) from public;
revoke all on function public.get_listing_agent_bidder_details(uuid) from public;
revoke all on function public.get_listing_agent_bid_history(uuid) from public;
grant execute on function public.place_max_offer(uuid, bigint) to authenticated;
grant execute on function public.get_public_offer_history(uuid) to anon, authenticated;
grant execute on function public.get_public_offer_summary(uuid) to anon, authenticated;
grant execute on function public.get_my_offer_status(uuid) to authenticated;
grant execute on function public.get_listing_agent_bidder_details(uuid) to authenticated;
grant execute on function public.get_listing_agent_bid_history(uuid) to authenticated;

commit;
